version: 0.0
os: linux
files:
  - source: src/AndrewHelen.com/AndrewHelen.com/build_output
    destination: /var/www/andrew-helen_com
hooks:
  ApplicationStart:
    - location: scripts/start_service.sh
      timeout: 300
      runas: root