version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
      dotnet: 3.1
      dotnet: 2.1
  pre_build:
    commands:
      - cd ./src/RichardGrace.com/RichardGrace.com && npm i && cd ../../..
      - cd ./src/AndrewHelen.com/AndrewHelen.com && npm i && cd ../../..
      - cd ./src/Nordicsoft.events/NordicSoftEvents && npm i && cd ../../..
  build:
    commands:
      - cd ./src/RichardGrace.com/RichardGrace.com && npm run buildspec_script  && cd ../../..
      - cd ./src/AndrewHelen.com/AndrewHelen.com && npm run buildspec_script  && cd ../../..
      - cd ./src/Nordicsoft.events/NordicSoftEvents && npm run buildspec_script && cd ../../..
artifacts:
  files:
    - src/RichardGrace.com/RichardGrace.com/build_output/**/*
    - src/AndrewHelen.com/AndrewHelen.com/build_output/**/*
    - src/Nordicsoft.events/NordicSoftEvents/build_output/**/*
    - scripts/**/*
    - appspec.yml