version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
      dotnet: 3.1
  pre_build:
    commands:
      - cd ./src/RichardGrace.com && npm i && cd ../..
  build:
    commands:
       - cd ./src/RichardGrace.com && npm run buildspec_script  && cd ../..
artifacts:
  files:
    - ./src/RichardGrace.com/build_output/**/*
    - scripts/**/*
    - appspec.yml